import { Licence } from '../models/Licence';

export const LICENSE_DATA: Licence[] = [
  {
    licId: 1,
    licNo: '0000169',
    licType: "Children's Residence",
    licName: 'Hatts Off Inc.',
    licPlace: 'Dundas',
    licPhone: '905-521-1555',
    licCondition: 'NA',
  },
  {
    licId: 2,
    licNo: '0000169',
    licType: "Children's Residence",
    licName: 'Hatts Off Inc.',
    licPlace: 'Dundas',
    licPhone: '905-521-1555',
    licCondition: 'NA',
  },
  {
    licId: 3,
    licNo: '0000169',
    licType: "Children's Residence",
    licName: 'Hatts Off Inc.',
    licPlace: 'Dundas',
    licPhone: '905-521-1555',
    licCondition: 'NA',
  },
  {
    licId: 4,
    licNo: '0000169',
    licType: "Children's Residence",
    licName: 'Hatts Off Inc.',
    licPlace: 'Dundas',
    licPhone: '905-521-1555',
    licCondition: 'NA',
  },
  {
    licId: 5,
    licNo: '0000169',
    licType: "Children's Residence",
    licName: 'Hatts Off Inc.',
    licPlace: 'Dundas',
    licPhone: '905-521-1555',
    licCondition: 'NA',
  },
  {
    licId: 6,
    licNo: '0000169',
    licType: "Children's Residence",
    licName: 'Hatts Off Inc.',
    licPlace: 'Dundas',
    licPhone: '905-521-1555',
    licCondition: 'NA',
  },
  {
    licId: 7,
    licNo: '0000169',
    licType: "Children's Residence",
    licName: 'Hatts Off Inc.',
    licPlace: 'Dundas',
    licPhone: '905-521-1555',
    licCondition: 'NA',
  },
  {
    licId: 8,
    licNo: '0000169',
    licType: "Children's Residence",
    licName: 'Hatts Off Inc.',
    licPlace: 'Dundas',
    licPhone: '905-521-1555',
    licCondition: 'NA',
  },
  {
    licId: 9,
    licNo: '0000169',
    licType: "Children's Residence",
    licName: 'Hatts Off Inc.',
    licPlace: 'Dundas',
    licPhone: '905-521-1555',
    licCondition: 'NA',
  },
  {
    licId: 10,
    licNo: '0000169',
    licType: "Children's Residence",
    licName: 'Hatts Off Inc.',
    licPlace: 'Dundas',
    licPhone: '905-521-1555',
    licCondition: 'NA',
  },
];
